tenant:
  id: tenant2
  name: "企业租户"

spring:
  application:
    name: tenant2-app

# 企业版特定配置
advanced:
  features:
    fraud-detection: true
    erp-integration: true
    advanced-analytics: true

logging:
  level:
    com.company.tenant2: DEBUG